/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * ChatterRealm API
 * API for ChatterRealm - A multiplayer emoji-based game world
 * OpenAPI spec version: 1.0.0
 */

export interface AIProxyRequest {
  /** Additional context */
  context?: string;
  /** AI model */
  model?: string;
  /**
   * AI prompt
   * @minLength 1
   */
  prompt: string;
}
