/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * ChatterRealm API
 * API for ChatterRealm - A multiplayer emoji-based game world
 * OpenAPI spec version: 1.0.0
 */

export interface Color {
  /**
   * Alpha component
   * @minimum 0
   * @maximum 1
   */
  a?: number;
  /**
   * Blue component
   * @minimum 0
   * @maximum 255
   */
  b: number;
  /**
   * Green component
   * @minimum 0
   * @maximum 255
   */
  g: number;
  /**
   * Red component
   * @minimum 0
   * @maximum 255
   */
  r: number;
}
