/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * ChatterRealm API
 * API for ChatterRealm - A multiplayer emoji-based game world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Character class
 */
export type CreatePlayerRequestClass = typeof CreatePlayerRequestClass[keyof typeof CreatePlayerRequestClass];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePlayerRequestClass = {
  warrior: 'warrior',
  mage: 'mage',
  rogue: 'rogue',
  cleric: 'cleric',
  ranger: 'ranger',
  paladin: 'paladin',
  druid: 'druid',
  bard: 'bard',
} as const;
