/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * ChatterRealm API
 * API for ChatterRealm - A multiplayer emoji-based game world
 * OpenAPI spec version: 1.0.0
 */
import type { CreatePlayerRequestClass } from './createPlayerRequestClass';
import type { Color } from './color';

export interface CreatePlayerRequest {
  /** Character class */
  class: CreatePlayerRequestClass;
  color: Color;
  /**
   * Player emoji
   * @minLength 1
   * @maxLength 4
   */
  emoji: string;
  /** Use hand-drawn emoji */
  isHandDrawn?: boolean;
  /**
   * Player name
   * @minLength 1
   * @maxLength 32
   */
  name: string;
}
