/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * ChatterRealm API
 * API for ChatterRealm - A multiplayer emoji-based game world
 * OpenAPI spec version: 1.0.0
 */
import type { Item } from './item';
import type { Npc } from './npc';
import type { Player } from './player';
import type { WorldState } from './worldState';

export interface GameWorld {
  /** World creation timestamp */
  createdAt: string;
  /**
   * World height
   * @minimum 1
   */
  height: number;
  /** World identifier */
  id: string;
  /** World items */
  items: Item[];
  /**
   * World name
   * @minLength 1
   */
  name: string;
  /** Active NPCs */
  npcs: Npc[];
  /** Active players */
  players: Player[];
  state: WorldState;
  /** Last world update */
  updatedAt: string;
  /**
   * World width
   * @minimum 1
   */
  width: number;
}
