/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * ChatterRealm API
 * API for ChatterRealm - A multiplayer emoji-based game world
 * OpenAPI spec version: 1.0.0
 */

export interface GameCommandRequest {
  /** Command arguments */
  args?: string[];
  /**
   * Game command
   * @minLength 1
   */
  command: string;
  /** Player identifier */
  playerId: string;
}
