/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * ChatterRealm API
 * API for ChatterRealm - A multiplayer emoji-based game world
 * OpenAPI spec version: 1.0.0
 */

export type GetEmojiParams = {
char: string;
rough?: boolean;
roughness?: number;
bowing?: number;
};
