/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * ChatterRealm API
 * API for ChatterRealm - A multiplayer emoji-based game world
 * OpenAPI spec version: 1.0.0
 */
import type { Vector2 } from './vector2';

export interface Item {
  /**
   * Item emoji representation
   * @minLength 1
   * @maxLength 4
   */
  emoji: string;
  /** Unique item identifier */
  id: string;
  /**
   * Item name
   * @minLength 1
   * @maxLength 64
   */
  name: string;
  position: Vector2;
  /** Item rarity */
  rarity: string;
  /**
   * Item type
   * @minLength 1
   */
  type: string;
  /**
   * Item value
   * @minimum 0
   */
  value: number;
}
