/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * ChatterRealm API
 * API for ChatterRealm - A multiplayer emoji-based game world
 * OpenAPI spec version: 1.0.0
 */
import type { MessageType } from './messageType';

export interface Message {
  /**
   * Message content
   * @minLength 1
   * @maxLength 512
   */
  content: string;
  /**
   * Sender emoji
   * @minLength 1
   * @maxLength 4
   */
  emoji?: string;
  /** Message identifier */
  id: string;
  /**
   * Message sender
   * @minLength 1
   */
  sender: string;
  /** Message timestamp */
  timestamp: string;
  /** Message type */
  type?: MessageType;
}
