/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * ChatterRealm API
 * API for ChatterRealm - A multiplayer emoji-based game world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Message type
 */
export type MessageType = typeof MessageType[keyof typeof MessageType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageType = {
  chat: 'chat',
  system: 'system',
  combat: 'combat',
  loot: 'loot',
} as const;
