/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * ChatterRealm API
 * API for ChatterRealm - A multiplayer emoji-based game world
 * OpenAPI spec version: 1.0.0
 */
import type { Vector2 } from './vector2';

export interface Npc {
  /** NPC behavior pattern */
  behavior: string;
  /** Available dialogue options */
  dialogue: string[];
  /**
   * NPC emoji representation
   * @minLength 1
   * @maxLength 4
   */
  emoji: string;
  /**
   * NPC health
   * @minimum 0
   */
  health: number;
  /** Unique NPC identifier */
  id: string;
  /**
   * NPC name
   * @minLength 1
   * @maxLength 64
   */
  name: string;
  position: Vector2;
  /**
   * NPC type
   * @minLength 1
   */
  type: string;
}
