/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * ChatterRealm API
 * API for ChatterRealm - A multiplayer emoji-based game world
 * OpenAPI spec version: 1.0.0
 */
import type { PlayerClass } from './playerClass';
import type { Color } from './color';
import type { Vector2 } from './vector2';

export interface Player {
  /** Player character class */
  class: PlayerClass;
  color: Color;
  /** Combat style preference */
  combatStyle?: string;
  /** Player creation timestamp */
  createdAt?: string;
  /**
   * Player emoji representation
   * @minLength 1
   * @maxLength 4
   */
  emoji: string;
  /**
   * Experience points
   * @minimum 0
   */
  experience: number;
  /**
   * Current health
   * @minimum 0
   * @maximum 100
   */
  health: number;
  /** Unique player identifier */
  id: string;
  /** Player inventory items */
  inventory: string[];
  /** Use hand-drawn emoji */
  isHandDrawn?: boolean;
  /** Last activity timestamp */
  lastActive: string;
  /**
   * Player level
   * @minimum 1
   */
  level: number;
  /** Loot preferences */
  lootPreferences?: string[];
  /**
   * Maximum health
   * @minimum 1
   * @maximum 200
   */
  maxHealth: number;
  /**
   * Player name
   * @minLength 1
   * @maxLength 32
   */
  name: string;
  position: Vector2;
  /** Active status effects */
  statusEffects: string[];
  /** Last update timestamp */
  updatedAt?: string;
}
