/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * ChatterRealm API
 * API for ChatterRealm - A multiplayer emoji-based game world
 * OpenAPI spec version: 1.0.0
 */
import type { WorldStatePhase } from './worldStatePhase';

export interface WorldState {
  /**
   * Cataclysm progress percentage
   * @minimum 0
   * @maximum 100
   */
  cataclysmProgress: number;
  /**
   * World corruption level
   * @minimum 0
   * @maximum 1
   */
  corruptionLevel: number;
  /**
   * Last cataclysm timestamp
   * @nullable
   */
  lastCataclysm: string | null;
  /** Current game phase */
  phase: WorldStatePhase;
  /**
   * Current world time
   * @minimum 0
   */
  time: number;
}
