/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * ChatterRealm API
 * API for ChatterRealm - A multiplayer emoji-based game world
 * OpenAPI spec version: 1.0.0
 */

/**
 * Current game phase
 */
export type WorldStatePhase = typeof WorldStatePhase[keyof typeof WorldStatePhase];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorldStatePhase = {
  peace: 'peace',
  cataclysm: 'cataclysm',
  recovery: 'recovery',
} as const;
